'use strict';
function updateThemeButton(){const dark=document.documentElement.dataset.theme==='dark';document.getElementById('themeToggle').textContent=`Dark mode: ${dark?'on':'off'}`;document.getElementById('themeToggle').setAttribute('aria-pressed',String(dark));}
document.getElementById('themeToggle').onclick=()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('kriegsspiel-theme',theme);}catch(e){}updateThemeButton();};
updateThemeButton();
const $=id=>document.getElementById(id), NS='http://www.w3.org/2000/svg', clone=x=>JSON.parse(JSON.stringify(x));
let state={version:1,title:'Pea Ridge · practice encounter',time:'10:00',map:'fake-pea-ridge-map.jpg',width:1408,height:768,metersPerPixel:10,calibrated:false,units:[],commanders:[]};
const uid=()=>crypto.randomUUID(), commander=(name)=>({id:uid(),name,notes:'',draft:{contacts:[],regions:[],briefing:''},published:{contacts:[],regions:[],briefing:'',time:'',title:'',at:null}});
state.commanders=[commander('Blue division'),commander('Red division')];
state.units=[{id:uid(),label:'1st Infantry',kind:'infantry',side:'blue',x:490,y:520,facing:0,strength:'450',activity:'Holding',notes:''},{id:uid(),label:'Ridge battery',kind:'artillery',side:'red',x:890,y:350,facing:25,strength:'4 guns',activity:'Deployed',notes:''}];
let active=state.commanders[0].id, selected=null,tool='select',points=[],measurement=null,history=[],box=[0,0,1408,768],drag=null;
const c=()=>state.commanders.find(x=>x.id===active), view=()=>$('view').value, knowledge=()=>view()==='published'?c().published:c().draft;
function remember(){history.push(clone(state));if(history.length>60)history.shift()}
function esc(s){return String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function node(tag,attrs,parent){const n=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);parent.append(n);return n}
function text(parent,x,y,value){const n=node('text',{x,y,'text-anchor':'middle'},parent);n.textContent=value;return n}
function sync(){ $('commander').innerHTML=state.commanders.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');$('commander').value=active;$('commanderName').value=c().name;$('commanderNotes').value=c().notes;$('briefing').value=c().draft.briefing;$('title').value=state.title;$('time').value=state.time;render();edit();}
function symbol(parent,r,contact=false){const g=node('g',{'data-id':r.id,'data-type':contact?'contact':'unit',transform:`translate(${r.x} ${r.y})`,style:'cursor:pointer'},parent),color={blue:'#375e79',red:'#994936',unknown:'#756e59'}[r.side]||'#756e59';
 if(contact&&+r.radius>0)node('circle',{r:r.radius/state.metersPerPixel,fill:color,'fill-opacity':.08,stroke:color,'stroke-dasharray':'5 5'},g);
 const outlined=contact&&r.presentation!=='confirmed'; const s=node('g',{transform:`rotate(${r.facing||0})`},g);
 if(r.kind==='marker'){node('path',{d:'M0 -13 L13 0 L0 13 L-13 0 Z',fill:outlined?'#fff7e3':color,stroke:color,'stroke-width':2},s);text(s,0,5,'?')}
 else {node('rect',{x:-24,y:-10,width:48,height:20,rx:1,fill:outlined?'#fff7e3':color,stroke:outlined?color:'#25362c','stroke-width':2,'stroke-dasharray':outlined?'4 2':'none'},s);const ink=outlined?color:'#fff7e3';if(r.kind==='infantry')node('path',{d:'M-22 -8 L22 8 M-22 8 L22 -8',stroke:ink,'stroke-width':1.4},s);if(r.kind==='cavalry')node('path',{d:'M-22 8 L22 -8',stroke:ink,'stroke-width':2},s);if(r.kind==='artillery'){for(const x of [-12,0,12])node('circle',{cx:x,cy:0,r:3,fill:ink},s)}if(r.kind==='hq'){const t=text(s,0,5,'HQ');t.setAttribute('fill',ink);t.setAttribute('stroke','none');t.setAttribute('font-size',12)}}
 text(g,0,29,r.label);if(contact&&r.observed)text(g,0,45,r.observed).setAttribute('font-size',11);if(selected?.id===r.id)node('rect',{x:-30,y:-16,width:60,height:32,fill:'none',stroke:'#c79225','stroke-width':3},g);return g;}
function render(){ $('calibrationMeasured').textContent=tool==='calibrate'&&points.length===2?`Current measured value: ${(Math.hypot(points[1][0]-points[0][0],points[1][1]-points[0][1])*state.metersPerPixel).toFixed(2)} m (${state.calibrated?'current scale':'provisional scale'})`:'Current measured value: select two points';$('terrain').setAttribute('href',state.map);$('terrain').setAttribute('width',state.width);$('terrain').setAttribute('height',state.height);$('map').setAttribute('viewBox',box.join(' '));for(const id of ['truth','contacts','regions','connections','measure'])$(id).replaceChildren();const k=knowledge();
 for(const r of k.regions){const p=node('polygon',{points:r.points.map(p=>p.join(',')).join(' '),fill:'#567d62','fill-opacity':.13,stroke:'#426b4b','stroke-width':3,'stroke-dasharray':'10 5','data-id':r.id,'data-type':'region'},$('regions'));if(selected?.id===r.id)p.setAttribute('stroke','#c79225')}
 if(view()==='truth'||view()==='overlay')for(const r of state.units)symbol($('truth'),r);
 if(view()!=='truth'){ $('contacts').setAttribute('opacity',view()==='overlay'?$('opacity').value:1);for(const r of k.contacts)symbol($('contacts'),r,true)}
 if(view()==='overlay'&&$('links').checked)for(const r of k.contacts){const u=state.units.find(u=>u.id===r.truthId);if(u)node('line',{x1:u.x,y1:u.y,x2:r.x,y2:r.y,stroke:'#6e664f','stroke-width':2,'stroke-dasharray':'3 5'},$('connections'))}
 const p=points.length?points:measurement?.points||[],measureKind=points.length?tool:measurement?.kind;
 const speed=Number($('routeSpeed').value),validSpeed=Number.isFinite(speed)&&speed>0;
 $('routeOptions').hidden=tool!=='ruler'&&measureKind!=='ruler';
 $('routeSpeedMessage').textContent=validSpeed?'Constant-speed estimate; no terrain or rest allowance.':'Enter a speed greater than zero to estimate time.';
 if(p.length){node('polyline',{points:p.map(x=>x.join(',')).join(' '),fill:'none',stroke:'#b27613','stroke-width':3},$('measure'));let d=0;for(let i=0;i<p.length;i++){const x=p[i];node('circle',{cx:x[0],cy:x[1],r:4,fill:'#b27613'},$('measure'));if(i>0)d+=Math.hypot(x[0]-p[i-1][0],x[1]-p[i-1][1]);if(measureKind==='ruler'){const meters=d*state.metersPerPixel;const label=text($('measure'),x[0],x[1]-14,`${meters.toFixed(0)} m · ${validSpeed?routeTime(meters,speed):'time unavailable'}`);label.setAttribute('font-size',12);}else if(i===p.length-1&&p.length>1)text($('measure'),x[0],x[1]-12,`${(d*state.metersPerPixel).toFixed(0)} m`);}if(measureKind==='circle'&&p.length===2)node('circle',{cx:p[0][0],cy:p[0][1],r:d,fill:'none',stroke:'#b27613','stroke-width':2},$('measure'))}
 $('scale').textContent=`${state.calibrated?'Calibrated':'Provisional scale'} · ${state.metersPerPixel.toFixed(2)} m / image pixel`;
 $('roster').innerHTML=(view()==='truth'?state.units:k.contacts).map(r=>`<button data-record="${r.id}">${esc(r.label)}</button>`).join('');}
function record(){if(!selected)return null;return selected.type==='unit'?state.units.find(x=>x.id===selected.id):selected.type==='region'?knowledge().regions.find(x=>x.id===selected.id):knowledge().contacts.find(x=>x.id===selected.id)}
const fields=['label','kind','side','facing','strength','activity','observed','radius','notes','presentation'];
function routeTime(meters,kph){const seconds=Math.round(meters*3.6/kph),hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60),remainder=seconds%60;return hours?`${hours}h ${minutes}m ${remainder}s`:`${minutes}m ${remainder}s`;}
$('routeSpeed').oninput=render;
function edit(){const r=record();$('editor').hidden=!r||selected.type==='region';$('empty').hidden=!!r&&selected.type!=='region';$('empty').textContent=r&&selected.type==='region'?'Visible area selected. Press Delete to remove it, or redraw an area.':'Select a unit, contact, marker, or visible area.';if(!r||selected.type==='region')return;for(const f of fields)$(f).value=r[f]??(f==='presentation'?'reported':'');$('falseContact').checked=!!r.falseContact;$('copyContact').hidden=selected.type!=='unit';for(const f of [...fields,'falseContact','delete','duplicate'])$(f).disabled=view()==='published';}
for(const f of fields)$(f).onchange=()=>{const r=record();if(!r||view()==='published')return;remember();r[f]=['facing','radius'].includes(f)?Number($(f).value):$(f).value;render()};$('falseContact').onchange=()=>{if(record()&&view()!=='published'){remember();record().falseContact=$('falseContact').checked}};
function choose(t){tool=t;points=[];$('calibration').hidden=t!=='calibrate';$('applyCalibration').disabled=true;document.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));$('status').textContent={select:'Select or drag counters. Delete removes the selected draft record.',pan:'Drag to pan the map.',unit:'Click to place a truth counter.',contact:'Click to place an independent commander contact.',marker:'Click to place a commander marker.',polygon:'Click boundary vertices, then Finish drawing. Select and delete an area to redraw it.',ruler:'Click route points, then Finish drawing.',circle:'Click center, then radius point.',calibrate:'Click two map points; enter their real-world distance.'}[t];render()}
document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>choose(b.dataset.tool));
function pos(e){const p=$('map').createSVGPoint();p.x=e.clientX;p.y=e.clientY;const v=p.matrixTransform($('map').getScreenCTM().inverse());return[v.x,v.y]}
$('map').onpointerdown=e=>{if(e.button!==0)return;const p=pos(e),target=e.target.closest('[data-id]');if(tool==='pan'){drag={type:'pan',start:p,box:[...box]};$('map').setPointerCapture(e.pointerId);return}if(tool==='select'){selected=target?{id:target.dataset.id,type:target.dataset.type}:null;const r=record();if(r&&selected.type!=='region'&&view()!=='published'){remember();drag={type:'record',r,offset:[r.x-p[0],r.y-p[1]]};$('map').setPointerCapture(e.pointerId)}render();edit();return}if(view()==='published'){alert('Choose truth, commander draft, or onion skin to edit.');return}
 if(['unit','contact','marker'].includes(tool)){remember();const r={id:uid(),label:tool==='unit'?'New regiment':tool==='marker'?'Map marker':'Reported infantry',kind:tool==='marker'?'marker':'infantry',side:tool==='unit'?'blue':'unknown',x:p[0],y:p[1],facing:0,strength:'',activity:'',observed:state.time,radius:0,notes:''};(tool==='unit'?state.units:c().draft.contacts).push(r);if(tool!=='unit'&&view()==='truth')$('view').value='overlay';if(tool==='unit'&&view()==='player')$('view').value='overlay';selected={id:r.id,type:tool==='unit'?'unit':'contact'};choose('select');edit();return}
 if(tool==='calibrate'&&points.length===2)points=[];points.push(p);if(tool==='calibrate'){$('applyCalibration').disabled=points.length!==2;$('calibrationMessage').textContent=points.length===2?'Enter the known distance and click Apply calibration.':'Click the second point.';}if(tool==='circle'&&points.length===2)finish();render();};
$('map').onpointermove=e=>{if(!drag)return;const p=pos(e);if(drag.type==='record'){drag.r.x=p[0]+drag.offset[0];drag.r.y=p[1]+drag.offset[1]}else{box[0]+=drag.start[0]-p[0];box[1]+=drag.start[1]-p[1]}render()};$('map').onpointerup=()=>drag=null;$('map').onpointercancel=()=>drag=null;
$('map').onwheel=e=>{e.preventDefault();const p=pos(e),f=e.deltaY>0?1.12:1/1.12;if(box[2]*f<100||box[2]*f>state.width*10)return;box=[p[0]+(box[0]-p[0])*f,p[1]+(box[1]-p[1])*f,box[2]*f,box[3]*f];render()};
function finish(){if(tool==='polygon'&&points.length>=3){remember();c().draft.regions.push({id:uid(),points:clone(points)});points=[];if(view()==='truth')$('view').value='overlay'}else if(tool==='calibrate'){return}else if(points.length>=2){measurement={kind:tool,points:clone(points)};points=[]}render()}
$('finish').onclick=finish;$('map').ondblclick=e=>{e.preventDefault();if(points.length>1&&Math.hypot(points.at(-1)[0]-points.at(-2)[0],points.at(-1)[1]-points.at(-2)[1])<1)points.pop();finish()};$('fit').onclick=()=>{box=[0,0,state.width,state.height];render()};$('clearMeasure').onclick=()=>{measurement=null;points=[];render()};
function remove(){if(!selected||view()==='published')return;remember();const a=selected.type==='unit'?state.units:selected.type==='region'?c().draft.regions:c().draft.contacts;const i=a.findIndex(x=>x.id===selected.id);if(i>=0)a.splice(i,1);selected=null;render();edit()}
$('delete').onclick=remove;$('duplicate').onclick=()=>{const r=record();if(!r||view()==='published')return;remember();const n={...clone(r),id:uid(),x:r.x+60,y:r.y+35,label:r.label+' copy'};(selected.type==='unit'?state.units:c().draft.contacts).push(n);selected.id=n.id;render();edit()};
$('copyContact').onclick=()=>{const r=record();if(selected?.type!=='unit'||!r)return;remember();const old=c().draft.contacts.find(x=>x.truthId===r.id);const safe={label:r.label,kind:r.kind,side:r.side,x:r.x,y:r.y,facing:r.facing,strength:r.strength,activity:r.activity,observed:state.time,radius:0};if(old)Object.assign(old,safe);else c().draft.contacts.push({...safe,id:uid(),truthId:r.id,notes:''});$('status').textContent='Copied to this commander’s draft. Publish when ready.';render()};
$('commander').onchange=()=>{active=$('commander').value;selected=null;sync()};$('addCommander').onclick=()=>{const name=prompt('Commander name');if(!name)return;remember();const n=commander(name);state.commanders.push(n);active=n.id;selected=null;sync()};for(const [id,key]of [['commanderName','name'],['commanderNotes','notes']])$(id).onchange=()=>{remember();c()[key]=$(id).value;sync()};$('briefing').onchange=()=>{remember();c().draft.briefing=$('briefing').value};for(const f of ['title','time'])$(f).onchange=()=>{remember();state[f]=$(f).value};$('view').onchange=()=>{selected=null;render();edit()};$('opacity').oninput=render;$('links').onchange=render;
function project(comm){const d=comm.draft;return{contacts:d.contacts.map(r=>{const o={};for(const f of ['id','label','kind','side','x','y','facing','strength','activity','observed','radius','presentation'])o[f]=r[f]??(f==='presentation'?'reported':'');return o}),regions:clone(d.regions),briefing:d.briefing,time:state.time,title:state.title,at:new Date().toISOString()}}
$('publish').onclick=()=>{remember();c().published=project(c());$('status').textContent=`Published ${c().name} at ${state.time}.`;render()};$('undo').onclick=()=>{if(history.length){state=history.pop();if(!state.commanders.some(x=>x.id===active))active=state.commanders[0].id;selected=null;sync()}};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
async function embeddedMap(){if(state.map.startsWith('data:'))return state.map;const img=new Image();img.src=state.map;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;canvas.getContext('2d').drawImage(img,0,0);return canvas.toDataURL('image/jpeg',.94)}
$('save').onclick=async()=>{try{const s=clone(state);s.map=await embeddedMap();download(new Blob([JSON.stringify(s,null,2)],{type:'application/json'}),'kriegsspiel-scenario.json')}catch(e){alert('Could not embed the map. Import it using Import map, then save again. '+e.message)}};
function read(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)})}
$('mapFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=await read(file),img=new Image();img.src=data;await img.decode();remember();state.map=data;state.width=img.naturalWidth;state.height=img.naturalHeight;state.calibrated=false;box=[0,0,state.width,state.height];render();$('status').textContent='New map loaded. Recalibrate scale; existing coordinates are retained.'}catch(err){alert('Map could not be loaded: '+err.message)}};
$('load').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const s=JSON.parse(await file.text());if(s.version!==1||!Array.isArray(s.units)||!s.commanders?.length||!Number.isFinite(s.width)||s.width<=0||!Number.isFinite(s.height)||s.height<=0||!Number.isFinite(s.metersPerPixel)||s.metersPerPixel<=0||!(s.map.startsWith('data:image/png')||s.map.startsWith('data:image/jpeg')||s.map==='fake-pea-ridge-map.jpg'))throw Error('Unsupported scenario');for(const comm of s.commanders)if(!Array.isArray(comm.draft.contacts)||!Array.isArray(comm.draft.regions)||!Array.isArray(comm.published.contacts)||!Array.isArray(comm.published.regions))throw Error('Invalid commander records');remember();state=s;active=s.commanders[0].id;selected=null;box=[0,0,s.width,s.height];sync()}catch(err){alert('Could not load scenario: '+err.message)}};
async function exportImage(){const pub=c().published;if(!pub.at)throw Error('Publish this commander’s draft before exporting.');const svg=document.createElementNS(NS,'svg');svg.setAttribute('xmlns',NS);svg.setAttribute('width',state.width);svg.setAttribute('height',state.height+90);svg.setAttribute('viewBox',`0 0 ${state.width} ${state.height+90}`);node('rect',{width:state.width,height:state.height+90,fill:'#faf4e4'},svg);node('image',{href:await embeddedMap(),width:state.width,height:state.height},svg);for(const r of pub.regions)node('polygon',{points:r.points.map(p=>p.join(',')).join(' '),fill:'#567d62','fill-opacity':.12,stroke:'#426b4b','stroke-width':2,'stroke-dasharray':'8 5'},svg);for(const r of pub.contacts){const g=symbol(svg,r,true);g.querySelectorAll('text').forEach(n=>{n.setAttribute('font-family','Georgia');n.setAttribute('font-size',n.getAttribute('font-size')||15);n.setAttribute('paint-order','stroke');n.setAttribute('stroke','#fff6dc');n.setAttribute('stroke-width',3)});g.querySelectorAll('[data-id]').forEach(n=>n.removeAttribute('data-id'));g.removeAttribute('data-id');g.removeAttribute('data-type');const highlight=g.querySelector('rect[stroke="#c79225"]');if(highlight)highlight.remove()}
 text(svg,state.width/2,state.height+30,`${pub.title} · ${c().name} · ${pub.time}`);const length=Math.min(150,state.width/5),y=state.height+55;node('path',{d:`M30 ${y-5} V${y+5} M30 ${y} H${30+length} M${30+length} ${y-5} V${y+5}`,stroke:'#283c30','stroke-width':2},svg);text(svg,30+length/2,y+22,`${Math.round(length*state.metersPerPixel)} m${state.calibrated?'':' (provisional)'}`);const data='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(svg)),img=new Image();img.src=data;await img.decode();const canvas=document.createElement('canvas');canvas.width=state.width;canvas.height=state.height+90;canvas.getContext('2d').drawImage(img,0,0);return canvas}
$('png').onclick=async()=>{try{const canvas=await exportImage();canvas.toBlob(b=>{if(b)download(b,`${c().name.replace(/[^a-z0-9]/gi,'-')}-map.png`)},'image/png')}catch(e){alert(e.message)}};
$('pdf').onclick=async()=>{const w=window.open('','_blank');if(!w){alert('Allow a popup to open the printable briefing.');return}w.document.write('<p>Preparing published briefing…</p>');try{const canvas=await exportImage(),p=c().published;w.document.open();w.document.write(`<!doctype html><html><head><title>${esc(c().name)} briefing</title><style>@page{size:A4 landscape;margin:12mm}body{font:12px Georgia;color:#263b2d}img{width:100%;max-height:165mm;object-fit:contain}table{width:100%;border-collapse:collapse}td,th{padding:7px;text-align:left;border-bottom:1px solid #ccc}h1{font-size:22px}.notes{white-space:pre-wrap}@media print{button{display:none}.summary{break-before:page}}</style></head><body><button onclick="window.print()">Print / Save as PDF</button><h1>${esc(p.title)} · ${esc(c().name)} · ${esc(p.time)}</h1><img src="${canvas.toDataURL('image/png')}"><section class="summary"><h1>Reported contacts</h1><table><thead><tr><th>Contact</th><th>Strength estimate</th><th>Activity</th><th>Observed</th></tr></thead><tbody>${p.contacts.map(r=>`<tr><td>${esc(r.label)}</td><td>${esc(r.strength)}</td><td>${esc(r.activity)}</td><td>${esc(r.observed)}</td></tr>`).join('')}</tbody></table><h2>Briefing</h2><div class="notes">${esc(p.briefing)}</div></section></body></html>`);w.document.close()}catch(e){w.close();alert(e.message)}};
document.onkeydown=e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if(e.key==='Escape'){drag=null;points=[];choose('select')}if(e.key==='Delete')remove()};
sync();



$('applyCalibration').onclick=()=>{if(points.length!==2)return;const pixels=Math.hypot(points[1][0]-points[0][0],points[1][1]-points[0][1]),value=Number($('calibrationDistance').value);if(!Number.isFinite(value)||value<=0||pixels<=0){$('calibrationMessage').textContent='Enter a positive distance and select two distinct points.';return;}remember();state.metersPerPixel=value/pixels;state.calibrated=true;measurement={kind:'ruler',points:clone(points)};choose('select');$('status').textContent=`Calibration applied: ${value} meters between selected points.`;};
$('calibrationDistance').onkeydown=e=>{if(e.key==='Enter')$('applyCalibration').click();};
