export const catalog = [
  {id: 'gondor-swords', name: 'Gondor swordsmen', faction: 'Gondor', kind: 'Infantry', height: 13.5, file: 'gondor-swordsmen-clean.png', note: 'Clean style · eight swordsmen'},
  {id: 'gondor-horse', name: 'Gondor mounted lancers', shortName: 'Gondor lancers', faction: 'Gondor', kind: 'Mounted', height: 20, file: 'gondor-lancer-profile.png', note: 'Clean style · mirrored horse profiles'},
  {id: 'orc-axes', name: 'Orc axemen', faction: 'Orcs', kind: 'Infantry', height: 13.5, file: 'orc-axemen-clean.png', note: 'Clean style · eight axemen'},
  {id: 'orc-wargs', name: 'Orc warg riders', faction: 'Orcs', kind: 'Mounted', height: 20, file: 'orc-warg-profile.png', note: 'Clean style · mirrored warg profiles'},
  {id: 'orc-warband', name: 'Orc warband', faction: 'Orcs', kind: 'Infantry', height: 14.136, file: 'orc-warband-unit-v2.png', note: 'Clean style · eight mixed warriors'},
  {id: 'gondor-spears', name: 'Gondor spearmen', faction: 'Gondor', kind: 'Infantry', height: 13.5, file: 'gondor-spearmen-unit.png', note: 'Original textured style · eight spearmen'},
  {id: 'gondor-archers', name: 'Gondor archers', faction: 'Gondor', kind: 'Infantry', height: 13.5, file: 'gondor-archers-clean.png', note: 'Clean style · eight foot archers'},
  {id: 'gondor-horse-archers', name: 'Gondor mounted archers', faction: 'Gondor', kind: 'Mounted', height: 20, file: 'gondor-mounted-archer-profile.png', note: 'Clean style · mirrored horse archer profiles'},
  {id: 'orc-archers', name: 'Orc archers', faction: 'Orcs', kind: 'Infantry', height: 13.5, file: 'orc-archers-clean.png', note: 'Clean style · eight foot archers'},
  {id: 'orc-warg-archers', name: 'Orc mounted archers', shortName: 'Orc warg archers', faction: 'Orcs', kind: 'Mounted', height: 20, file: 'orc-mounted-archer-profile.png', note: 'Clean style · mirrored warg archer profiles'},
  {id: 'rohan-spears', name: 'Rohan mounted spearmen', faction: 'Rohan', kind: 'Mounted', file: 'rohan-spearman-profile.png', note: 'Clean style · mounted spearmen · 40 × 20 mm'},
  {id: 'rohan-archers', name: 'Rohan mounted archers', faction: 'Rohan', kind: 'Mounted', file: 'rohan-archer-profile.png', note: 'Clean style · horse archers · 40 × 20 mm'},
  {id: 'rohan-guard', name: 'Rohan Royal Guard', faction: 'Rohan', kind: 'Mounted', file: 'rohan-royal-guard-profile.png', note: 'Clean style · mounted Royal Guard · 40 × 20 mm'},
  {id: 'rohan-charging-riders', name: 'Rohan charging riders', shortName: 'Rohan charging riders', faction: 'Rohan', kind: 'Mounted', file: 'rohan-charging-rider-profile.png', note: 'Charging variant · galloping horse · leveled lance · 40 × 20 mm'},
  {id: 'rohan-eowyn', name: 'Éowyn', faction: 'Rohan', kind: 'Mounted', hero: true, baseWidth: 20, baseDepth: 20, file: 'eowyn-mounted-profile.png', note: 'Mounted hero · one upright · 20 × 20 mm'},
  {id: 'gondor-captain', name: 'Gondor captain', faction: 'Gondor', kind: 'Mounted', hero: true, baseWidth: 20, baseDepth: 20, file: 'gondor-captain-profile.png', note: 'Generic mounted hero · sword · one upright · 20 × 20 mm'},
  {id: 'gondor-standard-bearer', name: 'Gondor herald', shortName: 'Gondor herald', faction: 'Gondor', kind: 'Mounted', hero: true, baseWidth: 20, baseDepth: 20, file: 'gondor-standard-bearer-profile.png', note: 'Generic mounted standard bearer · banner · one upright · 20 × 20 mm'},
  {id: 'gondor-captain-charging', name: 'Charging captain', faction: 'Gondor', kind: 'Mounted', hero: true, baseWidth: 20, baseDepth: 20, file: 'gondor-captain-charging-profile.png', note: 'Gondor hero · galloping horse · raised sword · 20 × 20 mm'},
  {id: 'gondor-herald-rearing', name: 'Rearing herald', faction: 'Gondor', kind: 'Mounted', hero: true, baseWidth: 20, baseDepth: 20, file: 'gondor-herald-rearing-profile.png', note: 'Gondor hero · rearing horse · billowing banner · 20 × 20 mm'},
  {id: 'orc-chieftain', name: 'Orc chieftain', faction: 'Orcs', kind: 'Mounted', hero: true, baseWidth: 20, baseDepth: 20, file: 'orc-chieftain-profile.png', note: 'Mounted hero · charging warg · raised axe · 20 × 20 mm'},
  {id: 'orc-herald', name: 'Orc herald', faction: 'Orcs', kind: 'Mounted', hero: true, baseWidth: 20, baseDepth: 20, file: 'orc-herald-profile.png', note: 'Mounted hero · prowling warg · ragged banner · 20 × 20 mm'},
  {id: 'orc-troll', name: 'Giant', faction: 'Orcs', kind: 'Monster', baseWidth: 40, baseDepth: 20, uprightCount: 1, panelHeight: 35, preserveAspect: true, file: 'orc-giant.png', note: 'Single slovenly giant · 35 mm tall panel · 40 × 20 mm base'},
  {id: 'orc-monstrosities', name: 'Trolls', faction: 'Orcs', kind: 'Monster', baseWidth: 40, baseDepth: 20, uprightCount: 1, panelHeight: 23, preserveAspect: true, file: 'orc-trolls.png', note: 'Two rotting Trolls · one 23 mm upright · 40 × 20 mm base'},
  {id: 'orc-ogres', name: 'Ogres', faction: 'Orcs', kind: 'Monster', baseWidth: 40, baseDepth: 20, uprightCount: 1, panelHeight: 23, preserveAspect: true, file: 'orc-ogres.png', note: 'Two ogres · one 23 mm upright · 40 × 20 mm base'},
].map(art => ({...art, path: `artwork/${art.faction}/${art.file}`}));
